"""自动驾驶场景核证领域包。"""

from .backend import ScenarioCertificationBackend
from .contracts import RunOutcome, ScenarioVersion, TestRun
from .errors import (
    CertificationError,
    ConflictError,
    CoverageError,
    NotFoundError,
    StateError,
)
from .models import (
    AmbientConditions,
    BatchStatus,
    CapabilityClaim,
    ClaimStatus,
    CoverageReport,
    Event,
    Evidence,
    ExpectedBehavior,
    FaultInjection,
    ForkResult,
    ImpactReport,
    PinCoverage,
    ReleaseBatch,
    ReviewVerdict,
    RoadEnvironment,
    ScenarioDefinition,
    ScenarioPin,
    TestRunRecord,
    TrafficParticipant,
    VerdictDecision,
    digest_payload,
)

__all__ = [
    "AmbientConditions",
    "BatchStatus",
    "CapabilityClaim",
    "CertificationError",
    "ClaimStatus",
    "ConflictError",
    "CoverageError",
    "CoverageReport",
    "Event",
    "Evidence",
    "ExpectedBehavior",
    "FaultInjection",
    "ForkResult",
    "ImpactReport",
    "NotFoundError",
    "PinCoverage",
    "ReleaseBatch",
    "ReviewVerdict",
    "RoadEnvironment",
    "RunOutcome",
    "ScenarioCertificationBackend",
    "ScenarioDefinition",
    "ScenarioPin",
    "ScenarioVersion",
    "StateError",
    "TestRun",
    "TestRunRecord",
    "TrafficParticipant",
    "VerdictDecision",
    "digest_payload",
]
